### PR TITLE
Safe update  of 'updatedList' on triggerOnChange

### PR DESCRIPTION
**Pull request by martinobordin**
this.checklist could be undefined when trying to read it to update 'updatedList '

### CODE REVIEW

**Comment by zourtney** [comment]
Looks good; I think this makes sense to merge. My only hesitation is that this is a functional change -- `@Input() checklist` now can be falsy.

I'm pretty sure I purposefully avoided handling this so I would catch cases where my API wasn't sending me a property (aka `undefined`) when I was expecting `[]`. But that's a really narrow use case.

For my curiosity, can you show me a quick snippet of the situation / data that inspired the pull request?

**Comment by martinobordin** [comment]
Same use case (api returns null instead of [] for empty properties)

**Comment by zourtney** [comment]
Gotcha. If you have no control over the API, this makes sense. Merged...

I will try to cut a new release today with this change in it.

**Comment by martinobordin** [comment]
Thanks

**Comment by zourtney** [comment]
Hey @martinobordin, I just published version 1.3.0 with and your other pull request merged in. Let me know if you have any issues, and thanks for contributing!

**Pull request merged**
